import ThemeContextProvider from "src/theme";
import Sidebar from "src/widgets/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "initial-scale=1, width=device-width",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeContextProvider>
        <body suppressHydrationWarning={true}>
          <Sidebar />
          {children}
        </body>
      </ThemeContextProvider>
    </html>
  );
}
