import ThemeContextProvider from "src/theme";

export const metadata = {
  title: "Next.js & mui boilerplate",
  description: "Generated by create next app",
  viewport: "initial-scale=1, width=device-width",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeContextProvider>
        <body suppressHydrationWarning={true}>{children}</body>
      </ThemeContextProvider>
    </html>
  );
}
